# Generated by Django 5.2.15 on 2026-07-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.AlterModelOptions(
            name="borrowing",
            options={
                "ordering": ["-borrowed_at"],
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["name"],
                "verbose_name": "Gênero",
                "verbose_name_plural": "Gêneros",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="sobrenome"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="catalog.author",
                verbose_name="autor",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, verbose_name="URL da capa"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="catalog.genre",
                verbose_name="gêneros",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(
                default=1, verbose_name="quantidade no acervo"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, verbose_name="título"),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to="catalog.book",
                verbose_name="livro",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrowed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="data do empréstimo"
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuário",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="due_date",
            field=models.DateField(verbose_name="data de devolução"),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="returned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data em que foi devolvido"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nome"),
        ),
    ]
